<template>
  <div class="page-container report-page">
    <SearchBar :model-value="filters" :fields="searchFields" @update:model-value="updateFilters" @search="load" @reset="reset" />
    <div class="report-kpis"><el-card shadow="never"><span>本期收款</span><strong class="success">{{formatCurrency(report.overview.receivedAmount)}}</strong></el-card><el-card shadow="never"><span>本期付款</span><strong>{{formatCurrency(report.overview.paidAmount)}}</strong></el-card><el-card shadow="never"><span>本期费用</span><strong class="danger">{{formatCurrency(report.overview.expenseAmount)}}</strong></el-card><el-card shadow="never"><span>销售毛利</span><strong>{{formatCurrency(grossProfit)}}</strong><small>销售收入 - 出库成本</small></el-card><el-card shadow="never"><span>应收余额</span><strong>{{formatCurrency(report.overview.receivableBalance)}}</strong></el-card><el-card shadow="never"><span>应付余额</span><strong>{{formatCurrency(report.overview.payableBalance)}}</strong></el-card></div>
    <el-alert v-if="drillText" :title="drillText" type="info" show-icon :closable="false" class="drill-alert"><template #default><el-button link type="primary" @click="clearDrill">清除下钻</el-button></template></el-alert>
    <div class="report-charts"><ReportChartCard title="收支趋势" description="已过账收款、付款、费用" :option="cashTrendOption" :loading="loading" filename="收支趋势.png" class="wide" /><ReportChartCard title="应收账龄分析" description="点击扇区下钻应收明细" :option="receivableAgeOption" :loading="loading" filename="应收账龄.png" @click="drillAge('receivable',$event)" /><ReportChartCard title="费用类别统计" description="按已过账费用单汇总" :option="expenseOption" :loading="loading" filename="费用分类.png" @click="drillExpense" /></div>
    <DataTable :data="receivableRows" :columns="columns" :loading="loading" :show-export="true" @export="handleExport"><template #toolbar><div class="table-title"><b>应收账龄明细</b><span>当前未核销应收，账龄按到期日计算</span></div></template><template #cell-customer="{row}"><div><b>{{row.customer?.name||'-'}}</b><small>{{row.customer?.code||'-'}}</small></div></template><template #cell-outstanding="{row}"><b>{{formatCurrency(row.outstanding_amount)}}</b></template><template #cell-age="{row}"><el-tag :type="ageBucket(row)==='90天以上'?'danger':ageBucket(row)==='未到期'?'success':'warning'" size="small">{{ageBucket(row)}}</el-tag></template></DataTable>
  </div>
</template>
<script setup>
import{computed,onMounted,reactive,ref}from'vue'
import{ElMessage}from'element-plus'
import DataTable from '@/components/common/DataTable.vue'
import SearchBar from '@/components/common/SearchBar.vue'
import ReportChartCard from '@/components/report/ReportChartCard.vue'
import{fetchFinanceReport,fetchReportOptions}from'@/api/report'
import{exportRowsToExcel}from'@/utils/excel'
import{formatCurrency,formatNumber}from'@/utils/format'
import{lineOption,pieOption,recentDateRange}from'@/utils/report'
const loading=ref(false),options=reactive({customers:[],suppliers:[]}),filters=reactive({date_range:recentDateRange(30),customer_id:'',supplier_id:''}),selectedAge=ref(''),selectedExpense=ref(''),report=reactive({overview:{receivedAmount:0,paidAmount:0,expenseAmount:0,receivableBalance:0,payableBalance:0,salesRevenue:0,salesCost:0},receivables:[],payables:[],receivableAgeing:[],payableAgeing:[],expenseByCategory:[],cashTrend:{labels:[],received:[],paid:[],expense:[]}})
const searchFields=computed(()=>[{key:'date_range',label:'业务期间',type:'daterange',width:'260px'},{key:'customer_id',label:'客户',type:'select',width:'190px',options:options.customers.map(r=>({label:`${r.code} · ${r.name}`,value:r.id}))},{key:'supplier_id',label:'供应商',type:'select',width:'190px',options:options.suppliers.map(r=>({label:`${r.code} · ${r.name}`,value:r.id}))}]);const grossProfit=computed(()=>Number(report.overview.salesRevenue||0)-Number(report.overview.salesCost||0));const grossMargin=computed(()=>Number(report.overview.salesRevenue||0)>0?grossProfit.value/Number(report.overview.salesRevenue||0):0);const receivableRows=computed(()=>report.receivables.filter(r=>Number(r.outstanding_amount||0)>0&&(!selectedAge.value||ageBucket(r)===selectedAge.value)));const drillText=computed(()=>selectedAge.value?`已下钻：应收账龄「${selectedAge.value}」`:selectedExpense.value?`已下钻：费用类别「${selectedExpense.value}」`:grossMargin.value?'':'' );const cashTrendOption=computed(()=>lineOption({labels:report.cashTrend.labels,series:[{name:'收款',data:report.cashTrend.received},{name:'付款',data:report.cashTrend.paid},{name:'费用',data:report.cashTrend.expense}],valueFormatter:v=>formatCurrency(v)}));const receivableAgeOption=computed(()=>pieOption({data:report.receivableAgeing,valueFormatter:v=>formatCurrency(v)}));const expenseOption=computed(()=>pieOption({data:report.expenseByCategory,valueFormatter:v=>formatCurrency(v)}));const columns=[{prop:'receivable_no',label:'应收单号',width:175},{prop:'customer',label:'客户',minWidth:180,slot:'cell-customer'},{prop:'bill_date',label:'立账日期',width:120},{prop:'due_date',label:'到期日期',width:120},{prop:'original_amount',label:'原始金额',width:130,align:'right',formatter:r=>formatCurrency(r.original_amount)},{prop:'received_amount',label:'已收金额',width:130,align:'right',formatter:r=>formatCurrency(r.received_amount)},{prop:'outstanding_amount',label:'未收余额',width:130,align:'right',slot:'cell-outstanding'},{prop:'age',label:'账龄',width:115,align:'center',slot:'cell-age'}]
function updateFilters(v){Object.assign(filters,v)}function ageBucket(row){const base=row.due_date||row.bill_date;if(!base)return'未到期';const days=Math.floor((Date.now()-new Date(`${base}T00:00:00`).getTime())/86400000);if(days<=0)return'未到期';if(days<=30)return'1-30天';if(days<=60)return'31-60天';if(days<=90)return'61-90天';return'90天以上'}async function load(){loading.value=true;try{Object.assign(report,await fetchFinanceReport(filters))}catch(e){ElMessage.error(e.message||'加载财务报表失败')}finally{loading.value=false}}async function reset(){Object.assign(filters,{date_range:recentDateRange(30),customer_id:'',supplier_id:''});clearDrill();await load()}function drillAge(_,event){const name=event?.name;if(name)selectedAge.value=name;selectedExpense.value=''}function drillExpense(event){if(event?.name){selectedExpense.value=event.name;selectedAge.value='';ElMessage.info(`费用类别「${event.name}」已在图表中定位；当前表格展示应收账龄明细。`)}}function clearDrill(){selectedAge.value='';selectedExpense.value=''}function handleExport(){const rows=receivableRows.value.map(r=>({应收单号:r.receivable_no,客户:r.customer?.name||'',立账日期:r.bill_date,到期日期:r.due_date,原始金额:Number(r.original_amount||0),已收金额:Number(r.received_amount||0),未收余额:Number(r.outstanding_amount||0),账龄:ageBucket(r)}));if(!exportRowsToExcel(rows,[],`财务报表_应收账龄_${filters.date_range.join('_')}.xlsx`,'应收账龄'))ElMessage.warning('暂无可导出数据')}onMounted(async()=>{try{Object.assign(options,await fetchReportOptions());await load()}catch(e){ElMessage.error(e.message||'初始化财务报表失败')}})
</script>
<style scoped>.report-kpis{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:12px;margin-bottom:16px}.report-kpis .el-card :deep(.el-card__body){padding:14px 16px}.report-kpis span,.report-kpis strong,.report-kpis small{display:block}.report-kpis span,.report-kpis small{font-size:12px;color:var(--el-text-color-secondary)}.report-kpis strong{margin-top:7px;font-size:19px}.success{color:var(--el-color-success)}.danger{color:var(--el-color-danger)}.drill-alert{margin-bottom:14px}.report-charts{display:grid;grid-template-columns:1.4fr 1fr 1fr;gap:16px;margin-bottom:16px}.wide{min-width:0}.table-title b,.table-title span{display:block}.table-title span,.data-table-card small{font-size:12px;color:var(--el-text-color-secondary);margin-top:3px}@media(max-width:1280px){.report-kpis{grid-template-columns:repeat(3,1fr)}.report-charts{grid-template-columns:1fr 1fr}.report-charts .wide{grid-column:span 2}}@media(max-width:720px){.report-kpis,.report-charts{grid-template-columns:1fr}.report-charts .wide{grid-column:auto}}</style>
