<template>
  <div class="page-container report-page">
    <SearchBar :model-value="filters" :fields="searchFields" @update:model-value="updateFilters" @search="load" @reset="reset" />
    <div class="report-kpis"><el-card shadow="never"><span>当前库存金额</span><strong>{{ formatCurrency(report.overview.stockValue) }}</strong></el-card><el-card shadow="never"><span>当前库存数量</span><strong>{{ formatNumber(report.overview.onHandQty,{maximumFractionDigits:3}) }}</strong></el-card><el-card shadow="never"><span>区间入库数量</span><strong class="success">{{ formatNumber(report.overview.inboundQty,{maximumFractionDigits:3}) }}</strong></el-card><el-card shadow="never"><span>区间出库数量</span><strong class="warning">{{ formatNumber(report.overview.outboundQty,{maximumFractionDigits:3}) }}</strong></el-card></div>
    <el-alert title="库存报表以当前库存为期末口径；期初数量按“当前库存 - 区间入库 + 区间出库”进行推算，适合经营分析，不替代会计存货结账。" type="info" :closable="false" show-icon class="inventory-note" />
    <el-alert v-if="drillText" :title="drillText" type="info" show-icon :closable="false" class="drill-alert"><template #default><el-button link type="primary" @click="clearDrill">清除下钻</el-button></template></el-alert>
    <div class="report-charts"><ReportChartCard title="仓库库存金额" description="点击柱状图按仓库下钻" :option="warehouseOption" :loading="loading" filename="仓库库存金额.png" @click="drillWarehouse" /><ReportChartCard title="滞销/久未出库商品" description="超过 90 天未出库或没有出库记录" :option="slowOption" :loading="loading" filename="滞销商品分析.png" @click="drillProduct" /></div>
    <DataTable :data="detailRows" :columns="columns" :loading="loading" :show-export="true" @export="handleExport"><template #toolbar><div class="table-title"><b>库存汇总</b><span>按商品、仓库、库位、批次维度展示</span></div></template><template #cell-product="{row}"><div><b>{{row.product?.name||'-'}}</b><small>{{row.product?.code||'-'}}</small></div></template><template #cell-warehouse="{row}">{{row.warehouse?.name||'-'}}{{row.location?.name?` / ${row.location.name}`:''}}</template><template #cell-opening="{row}">{{formatNumber(openingQty(row),{maximumFractionDigits:3})}}</template><template #cell-qty="{row}"><b>{{formatNumber(row.quantity_on_hand,{maximumFractionDigits:3})}}</b></template><template #cell-value="{row}">{{formatCurrency(row.total_cost)}}</template><template #cell-age="{row}"><el-tag :type="row.stock_age_days===null||row.stock_age_days>=90?'warning':'success'" size="small">{{ageText(row)}}</el-tag></template><template #cell-warning="{row}"><el-tag v-if="row.warning" type="danger" size="small">低于安全库存</el-tag><span v-else>-</span></template></DataTable>
  </div>
</template>
<script setup>
import{computed,onMounted,reactive,ref}from'vue'
import{ElMessage}from'element-plus'
import DataTable from '@/components/common/DataTable.vue'
import SearchBar from '@/components/common/SearchBar.vue'
import ReportChartCard from '@/components/report/ReportChartCard.vue'
import{fetchInventoryReport,fetchReportOptions}from '@/api/report'
import{exportRowsToExcel}from '@/utils/excel'
import{formatCurrency,formatNumber}from '@/utils/format'
import{barOption,recentDateRange}from '@/utils/report'
const loading=ref(false),options=reactive({warehouses:[],products:[]}),filters=reactive({date_range:recentDateRange(30),warehouse_id:'',product_id:''}),selectedWarehouseId=ref(''),selectedProductId=ref(''),report=reactive({overview:{stockValue:0,onHandQty:0,inboundQty:0,outboundQty:0,turnoverRate:0},details:[],warehouseRanking:[],slowMoving:[]})
const searchFields=computed(()=>[{key:'date_range',label:'业务期间',type:'daterange',width:'260px'},{key:'warehouse_id',label:'仓库',type:'select',width:'190px',options:options.warehouses.map(r=>({label:`${r.code} · ${r.name}`,value:r.id}))},{key:'product_id',label:'商品',type:'select',width:'220px',options:options.products.map(r=>({label:`${r.code} · ${r.name}`,value:r.id}))}]);const detailRows=computed(()=>report.details.filter(row=>(!selectedWarehouseId.value||row.warehouse_id===selectedWarehouseId.value)&&(!selectedProductId.value||row.product_id===selectedProductId.value)));const drillText=computed(()=>{const w=options.warehouses.find(r=>r.id===selectedWarehouseId.value),p=report.details.find(r=>r.product_id===selectedProductId.value)?.product;return w?`已下钻：仓库「${w.name}」`:p?`已下钻：商品「${p.name}」`:''});const warehouseOption=computed(()=>barOption({labels:report.warehouseRanking.map(r=>r.name),values:report.warehouseRanking.map(r=>r.value),seriesName:'库存金额',horizontal:true,valueFormatter:v=>formatCurrency(v)}));const slowOption=computed(()=>barOption({labels:report.slowMoving.slice(0,10).map(r=>r.product?.name||'-'),values:report.slowMoving.slice(0,10).map(r=>r.total_cost),seriesName:'库存金额',horizontal:true,valueFormatter:v=>formatCurrency(v)}));const columns=[{prop:'product',label:'商品',minWidth:180,slot:'cell-product'},{prop:'warehouse',label:'仓库/库位',minWidth:170,slot:'cell-warehouse'},{prop:'batch_no',label:'批次',width:130},{prop:'opening_qty',label:'推算期初',width:115,align:'right',slot:'cell-opening'},{prop:'in_qty',label:'本期入库',width:115,align:'right',formatter:r=>formatNumber(r.in_qty,{maximumFractionDigits:3})},{prop:'out_qty',label:'本期出库',width:115,align:'right',formatter:r=>formatNumber(r.out_qty,{maximumFractionDigits:3})},{prop:'quantity_on_hand',label:'期末库存',width:115,align:'right',slot:'cell-qty'},{prop:'quantity_available',label:'可用库存',width:115,align:'right',formatter:r=>formatNumber(r.quantity_available,{maximumFractionDigits:3})},{prop:'total_cost',label:'库存金额',width:135,align:'right',slot:'cell-value'},{prop:'stock_age_days',label:'库龄',width:115,align:'center',slot:'cell-age'},{prop:'warning',label:'预警',width:125,align:'center',slot:'cell-warning'}]
function updateFilters(v){Object.assign(filters,v)}function openingQty(row){return Number(row.quantity_on_hand||0)-Number(row.in_qty||0)+Number(row.out_qty||0)}function ageText(row){return row.stock_age_days===null?'无出库记录':`${row.stock_age_days} 天`}async function load(){loading.value=true;try{Object.assign(report,await fetchInventoryReport(filters))}catch(e){ElMessage.error(e.message||'加载库存报表失败')}finally{loading.value=false}}async function reset(){Object.assign(filters,{date_range:recentDateRange(30),warehouse_id:'',product_id:''});clearDrill();await load()}function drillWarehouse(e){const row=report.warehouseRanking.find(r=>r.name===e?.name);if(row){selectedWarehouseId.value=row.warehouse_id||options.warehouses.find(x=>x.name===row.name)?.id||'';selectedProductId.value=''}}function drillProduct(e){const row=report.slowMoving.find(r=>(r.product?.name||'-')===e?.name);if(row){selectedProductId.value=row.product_id;selectedWarehouseId.value=''}}function clearDrill(){selectedWarehouseId.value='';selectedProductId.value=''}function handleExport(){const rows=detailRows.value.map(r=>({商品编码:r.product?.code||'',商品名称:r.product?.name||'',仓库:r.warehouse?.name||'',库位:r.location?.name||'',批次:r.batch_no||'',推算期初:openingQty(r),本期入库:Number(r.in_qty||0),本期出库:Number(r.out_qty||0),期末库存:Number(r.quantity_on_hand||0),可用库存:Number(r.quantity_available||0),单位成本:Number(r.unit_cost||0),库存金额:Number(r.total_cost||0),库龄:r.stock_age_days===null?'无出库记录':r.stock_age_days,库存预警:r.warning?'是':'否'}));if(!exportRowsToExcel(rows,[],`库存汇总_${filters.date_range.join('_')}.xlsx`,'库存汇总'))ElMessage.warning('暂无可导出数据')}onMounted(async()=>{try{Object.assign(options,await fetchReportOptions());const{data,error}=await (await import('@/utils/supabase')).supabase.from('base_products').select('id,code,name').eq('status','active').order('code').limit(5000);if(error)throw error;options.products=data||[];await load()}catch(e){ElMessage.error(e.message||'初始化库存报表失败')}})
</script>
<style scoped>.report-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:16px}.report-kpis .el-card :deep(.el-card__body){padding:14px 16px}.report-kpis span,.report-kpis strong{display:block}.report-kpis span{font-size:13px;color:var(--el-text-color-secondary)}.report-kpis strong{margin-top:7px;font-size:21px}.success{color:var(--el-color-success)}.warning{color:var(--el-color-warning)}.inventory-note,.drill-alert{margin-bottom:14px}.report-charts{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:16px}.table-title b,.table-title span{display:block}.table-title span,.data-table-card small{font-size:12px;color:var(--el-text-color-secondary);margin-top:3px}@media(max-width:720px){.report-kpis,.report-charts{grid-template-columns:1fr}}</style>
