<template>
  <div class="page-container report-page">
    <SearchBar :model-value="filters" :fields="searchFields" @update:model-value="updateFilters" @search="load" @reset="reset" />
    <div class="report-kpis"><el-card shadow="never"><span>采购金额</span><strong>{{ formatCurrency(report.overview.totalAmount) }}</strong></el-card><el-card shadow="never"><span>收货数量</span><strong>{{ formatNumber(report.overview.totalQty,{maximumFractionDigits:3}) }}</strong></el-card><el-card shadow="never"><span>收货单数</span><strong>{{ formatNumber(report.overview.documentCount) }}</strong></el-card><el-card shadow="never"><span>合作供应商</span><strong>{{ formatNumber(report.overview.supplierCount) }}</strong></el-card></div>
    <el-alert v-if="drillText" :title="drillText" type="info" show-icon :closable="false" class="drill-alert"><template #default><el-button link type="primary" @click="clearDrill">清除下钻</el-button></template></el-alert>
    <div class="report-charts"><ReportChartCard title="采购趋势" description="按已过账收货单汇总" :option="trendOption" :loading="loading" filename="采购趋势.png" class="wide" /><ReportChartCard title="供应商采购排名" description="点击柱状图下钻到供应商明细" :option="supplierOption" :loading="loading" filename="供应商采购排名.png" @click="drillSupplier" /><ReportChartCard title="商品采购金额 TOP10" description="点击柱状图下钻到商品明细" :option="productOption" :loading="loading" filename="商品采购TOP10.png" @click="drillProduct" /></div>
    <DataTable :data="detailRows" :columns="columns" :loading="loading" :show-export="true" @export="handleExport"><template #toolbar><div class="table-title"><b>采购明细</b><span>已过账收货单明细行</span></div></template><template #cell-supplier="{row}"><div><b>{{row.supplier?.name||'-'}}</b><small>{{row.supplier?.code||'-'}}</small></div></template><template #cell-product="{row}"><div><b>{{row.product?.name||'-'}}</b><small>{{row.product?.code||'-'}}</small></div></template><template #cell-qty="{row}">{{formatNumber(row.qty,{maximumFractionDigits:3})}}</template><template #cell-amount="{row}"><b>{{formatCurrency(row.amount)}}</b></template></DataTable>
  </div>
</template>
<script setup>
import { computed,onMounted,reactive,ref } from 'vue'
import { ElMessage } from 'element-plus'
import DataTable from '@/components/common/DataTable.vue'
import SearchBar from '@/components/common/SearchBar.vue'
import ReportChartCard from '@/components/report/ReportChartCard.vue'
import {fetchPurchaseReport,fetchReportOptions} from '@/api/report'
import {exportRowsToExcel} from '@/utils/excel'
import {formatCurrency,formatNumber} from '@/utils/format'
import {barOption,lineOption,recentDateRange} from '@/utils/report'
const loading=ref(false);const options=reactive({suppliers:[],warehouses:[]});const filters=reactive({date_range:recentDateRange(30),supplier_id:'',warehouse_id:''});const selectedProductId=ref(''),selectedSupplierId=ref('');const report=reactive({overview:{totalAmount:0,totalQty:0,documentCount:0,supplierCount:0},trend:{labels:[],values:[]},suppliers:[],products:[],details:[]})
const searchFields=computed(()=>[{key:'date_range',label:'收货日期',type:'daterange',width:'260px'},{key:'supplier_id',label:'供应商',type:'select',width:'190px',options:options.suppliers.map(r=>({label:`${r.code} · ${r.name}`,value:r.id}))},{key:'warehouse_id',label:'仓库',type:'select',width:'180px',options:options.warehouses.map(r=>({label:`${r.code} · ${r.name}`,value:r.id}))}]);const flatRows=computed(()=>report.details.flatMap(receipt=>(receipt.items||[]).map(item=>({...item,receipt_no:receipt.receipt_no,receipt_date:receipt.receipt_date,supplier:receipt.supplier,warehouse:receipt.warehouse}))))
const detailRows=computed(()=>flatRows.value.filter(row=>(!selectedProductId.value||row.product_id===selectedProductId.value)&&(!selectedSupplierId.value||row.supplier?.id===selectedSupplierId.value)));const drillText=computed(()=>{const product=report.products.find(r=>r.id===selectedProductId.value),supplier=report.suppliers.find(r=>r.id===selectedSupplierId.value);return product?`已下钻：商品「${product.name}」`:supplier?`已下钻：供应商「${supplier.name}」`:''});const trendOption=computed(()=>lineOption({labels:report.trend.labels,series:[{name:'采购额',data:report.trend.values,areaStyle:{}}],valueFormatter:v=>formatCurrency(v)}));const supplierOption=computed(()=>barOption({labels:report.suppliers.slice(0,10).map(r=>r.name),values:report.suppliers.slice(0,10).map(r=>r.amount),seriesName:'采购额',horizontal:true,valueFormatter:v=>formatCurrency(v)}));const productOption=computed(()=>barOption({labels:report.products.slice(0,10).map(r=>r.name),values:report.products.slice(0,10).map(r=>r.amount),seriesName:'采购额',horizontal:true,valueFormatter:v=>formatCurrency(v)}));const columns=[{prop:'receipt_no',label:'收货单号',width:175},{prop:'receipt_date',label:'收货日期',width:120},{prop:'supplier',label:'供应商',minWidth:170,slot:'cell-supplier'},{prop:'product',label:'商品',minWidth:180,slot:'cell-product'},{prop:'qty',label:'数量',width:110,align:'right',slot:'cell-qty'},{prop:'unit_price',label:'单价',width:120,align:'right',formatter:r=>formatCurrency(r.unit_price)},{prop:'amount',label:'金额',width:130,align:'right',slot:'cell-amount'},{prop:'warehouse',label:'仓库',width:150,formatter:r=>r.warehouse?.name||'-'}]
function updateFilters(v){Object.assign(filters,v)}async function load(){loading.value=true;try{Object.assign(report,await fetchPurchaseReport(filters))}catch(e){ElMessage.error(e.message||'加载采购报表失败')}finally{loading.value=false}}async function reset(){Object.assign(filters,{date_range:recentDateRange(30),supplier_id:'',warehouse_id:''});clearDrill();await load()}function drillSupplier(e){const row=report.suppliers.find(i=>i.name===e?.name);if(row){selectedSupplierId.value=row.id;selectedProductId.value=''}}function drillProduct(e){const row=report.products.find(i=>i.name===e?.name);if(row){selectedProductId.value=row.id;selectedSupplierId.value=''}}function clearDrill(){selectedProductId.value='';selectedSupplierId.value=''}function handleExport(){const rows=detailRows.value.map(r=>({收货单号:r.receipt_no,收货日期:r.receipt_date,供应商:r.supplier?.name||'',商品编码:r.product?.code||'',商品名称:r.product?.name||'',数量:Number(r.qty||0),单价:Number(r.unit_price||0),金额:Number(r.amount||0),仓库:r.warehouse?.name||''}));if(!exportRowsToExcel(rows,[],`采购明细_${filters.date_range.join('_')}.xlsx`,'采购明细'))ElMessage.warning('暂无可导出数据')}onMounted(async()=>{try{Object.assign(options,await fetchReportOptions());await load()}catch(e){ElMessage.error(e.message||'初始化采购报表失败')}})
</script>
<style scoped>.report-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:16px}.report-kpis .el-card :deep(.el-card__body){padding:14px 16px}.report-kpis span,.report-kpis strong{display:block}.report-kpis span{font-size:13px;color:var(--el-text-color-secondary)}.report-kpis strong{margin-top:7px;font-size:21px}.report-charts{display:grid;grid-template-columns:1.2fr 1fr 1fr;gap:16px;margin-bottom:16px}.wide{min-width:0}.drill-alert{margin-bottom:14px}.table-title b,.table-title span{display:block}.table-title span,.data-table-card small{font-size:12px;color:var(--el-text-color-secondary);margin-top:3px}@media(max-width:1120px){.report-charts{grid-template-columns:1fr 1fr}.report-charts .wide{grid-column:span 2}}@media(max-width:720px){.report-kpis,.report-charts{grid-template-columns:1fr}.report-charts .wide{grid-column:auto}}</style>
