<template>
  <div class="page-container">
    <SearchBar :model-value="table.query" :fields="searchFields" @update:model-value="updateQuery" @search="table.search" @reset="table.reset" />
    <DataTable :data="table.rows" :columns="columns" :loading="table.loading" :pagination="table.pagination" :show-export="true" @page-change="table.changePage" @page-size-change="table.changePageSize" @sort-change="table.changeSort" @export="handleExport">
      <template #toolbar><el-button type="primary" :icon="Plus" @click="openCreate">新建调拨单</el-button></template>
      <template #cell-from="{row}">{{row.from_warehouse?.name||'-'}}</template><template #cell-to="{row}">{{row.to_warehouse?.name||'-'}}</template><template #cell-status="{row}"><el-tag :type="statusTagType(row.status)">{{transferStatus(row.status)}}</el-tag></template><template #cell-actions="{row}"><el-button link type="primary" @click="openEdit(row,row.status==='completed')">{{row.status==='draft'?'编辑':'详情'}}</el-button><el-button v-if="row.status!=='completed'&&row.status!=='cancelled'" link type="success" @click="post(row)">审核并完成</el-button></template>
    </DataTable>
    <el-dialog v-model="dialog.visible" :title="dialog.readonly?'调拨单详情':(form.id?'编辑调拨单':'新建调拨单')" width="1100px" top="5vh" :close-on-click-modal="false" destroy-on-close>
      <el-form ref="formRef" :model="form" :rules="rules" label-width="100px" :disabled="dialog.readonly">
        <el-row :gutter="18"><el-col :span="8"><el-form-item label="调出仓库" prop="from_warehouse_id"><el-select v-model="form.from_warehouse_id" filterable style="width:100%" @change="loadFromLocations"><el-option v-for="item in options.warehouses" :key="item.id" :label="`${item.code} · ${item.name}`" :value="item.id" /></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="调入仓库" prop="to_warehouse_id"><el-select v-model="form.to_warehouse_id" filterable style="width:100%" @change="loadToLocations"><el-option v-for="item in options.warehouses" :key="item.id" :label="`${item.code} · ${item.name}`" :value="item.id" /></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="调拨日期"><el-date-picker v-model="form.transfer_date" type="date" value-format="YYYY-MM-DD" style="width:100%" /></el-form-item></el-col><el-col :span="24"><el-form-item label="备注"><el-input v-model="form.remark" /></el-form-item></el-col></el-row>
        <el-divider content-position="left">调拨明细</el-divider><div class="line-toolbar"><el-button type="primary" plain :icon="Plus" :disabled="!form.from_warehouse_id" @click="selectorVisible=true">添加商品</el-button><el-button :icon="Delete" :disabled="!selected.length" @click="removeSelected">删除选中</el-button><span>完整过账会在一个数据库事务内执行“调出 + 调入”。</span></div>
        <el-table :data="form.items" border stripe max-height="390" @selection-change="selected=$event"><el-table-column type="selection" width="48"/><el-table-column type="index" label="#" width="52"/><el-table-column label="商品" min-width="210"><template #default="{row}"><b>{{row.product_name}}</b><small class="sub">{{row.product_code}}</small></template></el-table-column><el-table-column label="单位" width="90"><template #default="{row}">{{row.unit_name}}</template></el-table-column><el-table-column label="数量" width="145"><template #default="{row}"><el-input-number v-model="row.qty" :min="0.000001" :precision="6" controls-position="right" /></template></el-table-column><el-table-column label="调出库位" min-width="150"><template #default="{row}"><el-select v-model="row.from_location_id" clearable filterable style="width:100%"><el-option v-for="item in fromLocations" :key="item.id" :label="`${item.code} · ${item.name}`" :value="item.id" /></el-select></template></el-table-column><el-table-column label="调入库位" min-width="150"><template #default="{row}"><el-select v-model="row.to_location_id" clearable filterable style="width:100%"><el-option v-for="item in toLocations" :key="item.id" :label="`${item.code} · ${item.name}`" :value="item.id" /></el-select></template></el-table-column><el-table-column label="批次" width="130"><template #default="{row}"><el-input v-model="row.batch_no" /></template></el-table-column><el-table-column label="单位成本" width="140"><template #default="{row}"><el-input-number v-model="row.unit_cost" :min="0" :precision="4" controls-position="right" /></template></el-table-column></el-table>
      </el-form><template #footer><el-button @click="dialog.visible=false">{{dialog.readonly?'关闭':'取消'}}</el-button><el-button v-if="!dialog.readonly" type="primary" :loading="dialog.saving" @click="save">保存草稿</el-button></template>
    </el-dialog>
    <ProductSelector v-model="selectorVisible" :warehouse-id="form.from_warehouse_id" @select="appendProduct" />
  </div>
</template>

<script setup>
import { onMounted,reactive,ref } from 'vue'
import { ElMessage,ElMessageBox } from 'element-plus'
import { Delete,Plus } from '@element-plus/icons-vue'
import SearchBar from '@/components/common/SearchBar.vue';import DataTable from '@/components/common/DataTable.vue';import ProductSelector from '@/components/business/ProductSelector.vue';import {useTable} from '@/composables/useTable';import {fetchAllOptions,fetchWarehouseLocations,toDateString} from '@/api/business';import {fetchTransfers,getTransfer,postTransfer,saveTransfer} from '@/api/inventory';import{statusTagType}from '@/utils/format'
const table=useTable(fetchTransfers,{initialQuery:{keyword:'',status:'',from_warehouse_id:'',to_warehouse_id:'',date_range:[]},defaultSort:{prop:'transfer_date',order:'descending'}});const options=reactive({warehouses:[]});const fromLocations=ref([]);const toLocations=ref([]);const selected=ref([]);const selectorVisible=ref(false);const dialog=reactive({visible:false,readonly:false,saving:false});const formRef=ref(null);const form=reactive(emptyForm())
const searchFields=[{key:'keyword',label:'单据号',placeholder:'调拨单号或备注',width:'240px'},{key:'status',label:'状态',type:'select',width:'150px',options:[{label:'草稿',value:'draft'},{label:'已提交',value:'submitted'},{label:'已审核',value:'approved'},{label:'已完成',value:'completed'}]},{key:'date_range',label:'日期',type:'daterange',width:'260px'}];const columns=[{prop:'transfer_no',label:'调拨单号',width:175},{prop:'from',label:'调出仓库',minWidth:160,slot:'cell-from'},{prop:'to',label:'调入仓库',minWidth:160,slot:'cell-to'},{prop:'transfer_date',label:'调拨日期',width:120},{prop:'status',label:'状态',width:120,align:'center',slot:'cell-status'},{prop:'actions',label:'操作',width:170,fixed:'right',slot:'cell-actions',showOverflowTooltip:false,exportable:false}];const rules={from_warehouse_id:[{required:true,message:'请选择调出仓库',trigger:'change'}],to_warehouse_id:[{required:true,message:'请选择调入仓库',trigger:'change'}]}
function emptyForm(){return{id:'',from_warehouse_id:'',to_warehouse_id:'',transfer_date:toDateString(),remark:'',items:[]}};function updateQuery(v){Object.assign(table.query,v)};function transferStatus(s){return({draft:'草稿',submitted:'已提交',approved:'已审核',outbound_posted:'已出库',in_transit:'在途',completed:'已完成',cancelled:'已取消'})[s]||s}
async function loadFromLocations(){fromLocations.value=await fetchWarehouseLocations(form.from_warehouse_id)};async function loadToLocations(){toLocations.value=await fetchWarehouseLocations(form.to_warehouse_id)};function appendProduct(p){const has=form.items.find(x=>x.product_id===p.id);if(has){has.qty=Number(has.qty||0)+1}else{form.items.push({product_id:p.id,product_code:p.code,product_name:p.name,unit_id:p.base_unit_id,unit_name:p.unit?.name||'',qty:1,from_location_id:null,to_location_id:null,batch_no:'',unit_cost:Number(p.purchase_price||0)})}}
function removeSelected(){const ids=new Set(selected.value.map(x=>x.product_id));form.items=form.items.filter(x=>!ids.has(x.product_id));selected.value=[]};function resetForm(){Object.assign(form,emptyForm());fromLocations.value=[];toLocations.value=[]};function openCreate(){resetForm();dialog.readonly=false;dialog.visible=true}
async function openEdit(row,readonly=false){try{const detail=await getTransfer(row.id);resetForm();Object.assign(form,{...detail,items:(detail.items||[]).map(i=>({...i,product_code:i.product?.code,product_name:i.product?.name,unit_name:i.unit?.name}))});await Promise.all([loadFromLocations(),loadToLocations()]);dialog.readonly=readonly;dialog.visible=true}catch(e){ElMessage.error(e.message||'加载调拨单失败')}}
async function save(){try{await formRef.value?.validate();if(form.from_warehouse_id===form.to_warehouse_id)throw new Error('调出仓库和调入仓库不能相同');if(!form.items.length)throw new Error('请至少添加一行调拨明细');dialog.saving=true;await saveTransfer(form);ElMessage.success('调拨单已保存');dialog.visible=false;await table.load()}catch(e){if(e?.message)ElMessage.error(e.message||'保存失败')}finally{dialog.saving=false}}
async function post(row){try{await ElMessageBox.confirm(`确认审核并完成 ${row.transfer_no} 吗？系统将以单个事务完成调出、调入和库存流水。`,'调拨过账',{type:'warning'});await postTransfer(row.id);ElMessage.success('调拨已完成');await table.load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message||'调拨过账失败')}}
function handleExport({columns}){table.exportExcel({filename:`库存调拨_${toDateString()}.xlsx`,columns})};onMounted(async()=>{try{const data=await fetchAllOptions();options.warehouses=data.warehouses;await table.load()}catch(e){ElMessage.error(e.message||'加载页面失败')}})
</script>
<style scoped>.line-toolbar{display:flex;align-items:center;gap:10px;margin-bottom:12px;color:var(--el-text-color-secondary);font-size:13px}.sub{display:block;color:var(--el-text-color-secondary);margin-top:3px}</style>
