<template>
  <div class="page-container">
    <SearchBar :model-value="table.query" :fields="searchFields" @update:model-value="updateQuery" @search="table.search" @reset="table.reset" />
    <DataTable :data="table.rows" :columns="columns" :loading="table.loading" :pagination="table.pagination" :show-export="true" @page-change="table.changePage" @page-size-change="table.changePageSize" @sort-change="table.changeSort" @export="handleExport">
      <template #toolbar><el-button type="primary" :icon="Plus" @click="openCreate">新建盘点单</el-button></template>
      <template #cell-warehouse="{row}">{{row.warehouse?.name||'-'}}</template><template #cell-category="{row}">{{row.category?.name||'全仓库'}}</template><template #cell-gain="{row}">{{formatCurrency(row.gain_amount)}}</template><template #cell-loss="{row}">{{formatCurrency(row.loss_amount)}}</template><template #cell-status="{row}"><el-tag :type="statusTagType(row.status)">{{statusLabel(row.status)}}</el-tag></template>
      <template #cell-actions="{row}"><el-button link type="primary" @click="openEdit(row,row.status==='posted')">{{row.status==='draft'||row.status==='in_progress'||row.status==='submitted'?'盘点':'详情'}}</el-button><el-button v-if="row.status==='submitted'||row.status==='in_progress'" link type="success" @click="post(row)">审核并过账</el-button></template>
    </DataTable>
    <el-dialog v-model="dialog.visible" :title="dialog.readonly?'盘点单详情':(form.id?'盘点录入':'新建盘点任务')" width="1160px" top="4vh" :close-on-click-modal="false" destroy-on-close>
      <el-form ref="formRef" :model="form" :rules="rules" label-width="100px" :disabled="dialog.readonly">
        <el-row :gutter="18"><el-col :span="8"><el-form-item label="盘点仓库" prop="warehouse_id"><el-select v-model="form.warehouse_id" filterable style="width:100%"><el-option v-for="item in options.warehouses" :key="item.id" :label="`${item.code} · ${item.name}`" :value="item.id" /></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="商品分类"><el-select v-model="form.category_id" clearable filterable style="width:100%"><el-option v-for="item in options.categories" :key="item.id" :label="`${item.code} · ${item.name}`" :value="item.id" /></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="盘点日期"><el-date-picker v-model="form.stocktake_date" type="date" value-format="YYYY-MM-DD" style="width:100%" /></el-form-item></el-col><el-col :span="24"><el-form-item label="备注"><el-input v-model="form.remark" /></el-form-item></el-col></el-row>
        <div v-if="!form.id && !dialog.readonly" class="stocktake-create"><el-alert title="先保存盘点任务，再点击“生成盘点明细”。系统会按当前库存快照创建账面数量。" type="info" :closable="false" /><el-button type="primary" :loading="dialog.saving" @click="createAndPrepare">保存并生成盘点明细</el-button></div>
        <template v-else>
          <div class="line-toolbar"><el-button v-if="!dialog.readonly" @click="prepare" :loading="preparing">重新生成待盘点明细</el-button><span>盘点录入后会展示盘盈/盘亏差异；过账后自动写入库存流水。</span></div>
          <el-table :data="form.items" border stripe max-height="460"><el-table-column type="index" label="#" width="52"/><el-table-column label="商品" min-width="210"><template #default="{row}"><b>{{row.product_name}}</b><small class="sub">{{row.product_code}}</small></template></el-table-column><el-table-column label="库位" min-width="130"><template #default="{row}">{{row.location_name||'默认库位'}}</template></el-table-column><el-table-column label="批次" width="130" prop="batch_no"/><el-table-column label="账面数量" width="130" align="right"><template #default="{row}">{{formatNumber(row.book_qty,{maximumFractionDigits:6})}}</template></el-table-column><el-table-column label="实际数量" width="145"><template #default="{row}"><el-input-number v-model="row.actual_qty" :min="0" :precision="6" controls-position="right" @change="calc" /></template></el-table-column><el-table-column label="差异数量" width="135" align="right"><template #default="{row}"><span :class="diffClass(row)">{{formatNumber(diffQty(row),{maximumFractionDigits:6})}}</span></template></el-table-column><el-table-column label="单位成本" width="130" align="right"><template #default="{row}">{{formatCurrency(row.unit_cost)}}</template></el-table-column><el-table-column label="差异金额" width="140" align="right"><template #default="{row}"><span :class="diffClass(row)">{{formatCurrency(diffAmount(row))}}</span></template></el-table-column><el-table-column label="备注" min-width="150"><template #default="{row}"><el-input v-model="row.remark" /></template></el-table-column></el-table>
          <div class="total">盘盈金额：<b class="gain">{{formatCurrency(gainAmount)}}</b>；盘亏金额：<b class="loss">{{formatCurrency(lossAmount)}}</b></div>
        </template>
      </el-form>
      <template #footer><el-button @click="dialog.visible=false">{{dialog.readonly?'关闭':'取消'}}</el-button><el-button v-if="form.id&&!dialog.readonly" type="primary" :loading="dialog.saving" @click="saveItems">提交盘点数据</el-button></template>
    </el-dialog>
  </div>
</template>

<script setup>
import { computed,onMounted,reactive,ref } from 'vue'
import { ElMessage,ElMessageBox } from 'element-plus'
import { Plus } from '@element-plus/icons-vue'
import SearchBar from '@/components/common/SearchBar.vue'; import DataTable from '@/components/common/DataTable.vue'; import { useTable } from '@/composables/useTable'; import { supabase } from '@/utils/supabase'; import { fetchAllOptions,toDateString,numberValue } from '@/api/business'; import { fetchStocktakes,getStocktake,postStocktake,prepareStocktakeItems,saveStocktakeHeader,saveStocktakeItems } from '@/api/inventory'; import {formatCurrency,formatNumber,statusLabel,statusTagType} from '@/utils/format'
const table=useTable(fetchStocktakes,{initialQuery:{keyword:'',status:'',warehouse_id:'',category_id:'',date_range:[]},defaultSort:{prop:'stocktake_date',order:'descending'}}); const options=reactive({warehouses:[],categories:[]}); const dialog=reactive({visible:false,readonly:false,saving:false});const formRef=ref(null);const form=reactive(emptyForm());const preparing=ref(false)
const searchFields=[{key:'keyword',label:'单据号',placeholder:'盘点单号或备注',width:'230px'},{key:'warehouse_id',label:'仓库',type:'select',width:'180px',options:[]},{key:'status',label:'状态',type:'select',width:'130px',options:[{label:'草稿',value:'draft'},{label:'盘点中',value:'in_progress'},{label:'已提交',value:'submitted'},{label:'已过账',value:'posted'}]},{key:'date_range',label:'日期',type:'daterange',width:'260px'}]
const columns=[{prop:'stocktake_no',label:'盘点单号',width:175},{prop:'warehouse',label:'仓库',minWidth:150,slot:'cell-warehouse'},{prop:'category',label:'盘点范围',minWidth:140,slot:'cell-category'},{prop:'stocktake_date',label:'盘点日期',width:120},{prop:'gain',label:'盘盈金额',width:140,align:'right',slot:'cell-gain'},{prop:'loss',label:'盘亏金额',width:140,align:'right',slot:'cell-loss'},{prop:'status',label:'状态',width:110,align:'center',slot:'cell-status'},{prop:'actions',label:'操作',width:180,fixed:'right',slot:'cell-actions',showOverflowTooltip:false,exportable:false}]
const rules={warehouse_id:[{required:true,message:'请选择盘点仓库',trigger:'change'}]}; const gainAmount=computed(()=>form.items.reduce((s,x)=>s+Math.max(diffAmount(x),0),0));const lossAmount=computed(()=>form.items.reduce((s,x)=>s+Math.abs(Math.min(diffAmount(x),0)),0))
function emptyForm(){return{id:'',warehouse_id:'',category_id:'',stocktake_date:toDateString(),scope_type:'warehouse',status:'draft',remark:'',items:[]}}; function updateQuery(v){Object.assign(table.query,v)};function diffQty(row){return row.actual_qty===null||row.actual_qty===''||row.actual_qty===undefined?0:numberValue(row.actual_qty)-numberValue(row.book_qty)};function diffAmount(row){return Number((diffQty(row)*numberValue(row.unit_cost)).toFixed(2))};function diffClass(row){return{'diff-gain':diffQty(row)>0,'diff-loss':diffQty(row)<0}};function calc(){form.items=[...form.items]}
async function loadOptions(){const [data,cat]=await Promise.all([fetchAllOptions(),supabase.from('base_product_categories').select('id,code,name').eq('status','active').order('sort_order')]);if(cat.error)throw new Error(cat.error.message);options.warehouses=data.warehouses;options.categories=cat.data||[];searchFields[1].options=data.warehouses.map(i=>({label:`${i.code} · ${i.name}`,value:i.id}))}
function resetForm(){Object.assign(form,emptyForm())};function openCreate(){resetForm();dialog.readonly=false;dialog.visible=true}
async function openEdit(row,readonly=false){try{const detail=await getStocktake(row.id);resetForm();Object.assign(form,{...detail,items:(detail.items||[]).map(i=>({...i,product_code:i.product?.code,product_name:i.product?.name,location_name:i.location?.name}))});dialog.readonly=readonly;dialog.visible=true}catch(e){ElMessage.error(e.message||'加载盘点单失败')}}
async function createAndPrepare(){try{await formRef.value?.validate();dialog.saving=true;const detail=await saveStocktakeHeader(form);Object.assign(form,{...detail,items:[]});await prepare();ElMessage.success('盘点明细已生成')}catch(e){if(e?.message)ElMessage.error(e.message||'创建盘点任务失败')}finally{dialog.saving=false}}
async function prepare(){try{preparing.value=true;await prepareStocktakeItems(form.id);const detail=await getStocktake(form.id);form.items=(detail.items||[]).map(i=>({...i,product_code:i.product?.code,product_name:i.product?.name,location_name:i.location?.name}));form.status=detail.status;ElMessage.success('已按当前库存重新生成盘点明细')}catch(e){ElMessage.error(e.message||'生成盘点明细失败')}finally{preparing.value=false}}
async function saveItems(){try{if(!form.items.length)throw new Error('没有盘点明细');dialog.saving=true;await saveStocktakeItems(form.id,form.items);ElMessage.success('盘点数据已提交');dialog.visible=false;await table.load()}catch(e){if(e?.message)ElMessage.error(e.message||'提交盘点失败')}finally{dialog.saving=false}}
async function post(row){try{await ElMessageBox.confirm(`确认审核并过账 ${row.stocktake_no} 吗？盘盈盘亏会直接变更库存。`,'盘点过账',{type:'warning'});await postStocktake(row.id);ElMessage.success('盘点已过账');await table.load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message||'盘点过账失败')}}
function handleExport({columns}){table.exportExcel({filename:`库存盘点_${toDateString()}.xlsx`,columns})};onMounted(async()=>{try{await loadOptions();await table.load()}catch(e){ElMessage.error(e.message||'加载页面失败')}})
</script>
<style scoped>.stocktake-create{display:flex;align-items:center;gap:16px;padding:20px 0}.stocktake-create .el-alert{flex:1}.line-toolbar{display:flex;align-items:center;gap:12px;margin-bottom:12px;color:var(--el-text-color-secondary);font-size:13px}.sub{display:block;color:var(--el-text-color-secondary);margin-top:3px}.total{text-align:right;padding:12px;background:#fafafa}.gain,.diff-gain{color:var(--el-color-success)}.loss,.diff-loss{color:var(--el-color-danger)}</style>
