<template>
  <div class="page-container">
    <SearchBar :model-value="table.query" :fields="searchFields" @update:model-value="updateQuery" @search="table.search" @reset="table.reset" />
    <DataTable :data="table.rows" :columns="columns" :loading="table.loading" :pagination="table.pagination" :show-export="true" @page-change="table.changePage" @page-size-change="table.changePageSize" @sort-change="table.changeSort" @export="handleExport">
      <template #cell-product="{row}"><div><b>{{row.product?.name||'-'}}</b><small class="sub">{{row.product?.code}}{{row.product?.model?` · ${row.product.model}`:''}}</small></div></template><template #cell-warehouse="{row}">{{row.warehouse?.name||'-'}}{{row.location?.name?` / ${row.location.name}`:''}}</template><template #cell-direction="{row}"><el-tag :type="row.direction==='in'?'success':'danger'">{{row.direction==='in'?'入库':'出库'}}</el-tag></template><template #cell-qty="{row}"><span :class="row.direction==='in'?'in':'out'">{{row.direction==='in'?'+':'-'}}{{formatNumber(row.qty,{maximumFractionDigits:6})}}</span></template><template #cell-amount="{row}">{{formatCurrency(row.amount)}}</template>
    </DataTable>
  </div>
</template>
<script setup>
import {onMounted,reactive}from'vue';import{ElMessage}from'element-plus';import SearchBar from '@/components/common/SearchBar.vue';import DataTable from '@/components/common/DataTable.vue';import{useTable}from'@/composables/useTable';import{fetchAllOptions,toDateString}from'@/api/business';import{fetchStockFlows}from'@/api/inventory';import{formatCurrency,formatDateTime,formatNumber}from'@/utils/format'
const table=useTable(fetchStockFlows,{initialQuery:{keyword:'',transaction_type:'',direction:'',warehouse_id:'',date_range:[]},defaultSort:{prop:'transaction_at',order:'descending'}});const options=reactive({warehouses:[]});const searchFields=[{key:'keyword',label:'关键字',placeholder:'流水号、来源单号或备注',width:'260px'},{key:'transaction_type',label:'业务类型',type:'select',width:'170px',options:[{label:'采购收货',value:'purchase_receipt'},{label:'采购退货',value:'purchase_return'},{label:'销售发货',value:'sales_delivery'},{label:'销售退货',value:'sales_return'},{label:'库存调整',value:'adjustment_gain'},{label:'调拨出库',value:'transfer_out'},{label:'调拨入库',value:'transfer_in'}]},{key:'direction',label:'方向',type:'select',width:'120px',options:[{label:'入库',value:'in'},{label:'出库',value:'out'}]},{key:'warehouse_id',label:'仓库',type:'select',width:'170px',options:[]},{key:'date_range',label:'时间范围',type:'daterange',width:'260px'}];const columns=[{prop:'transaction_no',label:'流水号',width:170},{prop:'transaction_at',label:'发生时间',width:180,formatter:(r)=>formatDateTime(r.transaction_at)},{prop:'transaction_type',label:'业务类型',width:150,formatter:(r)=>typeLabel(r.transaction_type)},{prop:'product',label:'商品',minWidth:220,slot:'cell-product'},{prop:'warehouse',label:'仓库/库位',minWidth:170,slot:'cell-warehouse'},{prop:'batch_no',label:'批次',width:130},{prop:'direction',label:'方向',width:90,align:'center',slot:'cell-direction'},{prop:'qty',label:'数量',width:125,align:'right',slot:'cell-qty'},{prop:'before_qty',label:'变动前',width:115,align:'right'},{prop:'after_qty',label:'变动后',width:115,align:'right'},{prop:'amount',label:'金额',width:135,align:'right',slot:'cell-amount'},{prop:'source_no',label:'来源单据',width:170}]
function updateQuery(v){Object.assign(table.query,v)};function typeLabel(v){return({purchase_receipt:'采购收货',purchase_return:'采购退货',sales_delivery:'销售发货',sales_return:'销售退货',adjustment_gain:'库存调盈',adjustment_loss:'库存调亏',stocktake_gain:'盘盈',stocktake_loss:'盘亏',transfer_out:'调拨出库',transfer_in:'调拨入库',opening_balance:'期初库存'})[v]||v};function handleExport({columns}){table.exportExcel({filename:`库存流水_${toDateString()}.xlsx`,columns})};onMounted(async()=>{try{const data=await fetchAllOptions();options.warehouses=data.warehouses;searchFields[3].options=data.warehouses.map(i=>({label:`${i.code} · ${i.name}`,value:i.id}));await table.load()}catch(e){ElMessage.error(e.message||'加载库存流水失败')}})
</script><style scoped>.sub{display:block;color:var(--el-text-color-secondary);margin-top:3px}.in{color:var(--el-color-success);font-weight:700}.out{color:var(--el-color-danger);font-weight:700}</style>
